name: Markdown style checks

on:
  push:
    branches:
      - main
      - devel
    paths:
      - 'docs/**'   # Only run on changes to the docs directory
  pull_request:
    branches:
      - '*'
    paths:
      - 'docs/**'   # Only run on changes to the docs directory

jobs:
  markdown-lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: DavidAnson/markdownlint-cli2-action@v16
      with:
        config: "docs/.sphinx/.markdownlint.json"
